### ISSUE TITLE
Client topology calculations are not functioning

### ISSUE THREAD

**Issue by mattackerman808** [polaris-gslb/polaris-gslb#16]
The mapping works when loading the initial config and mapping servers to regions, however I can not get the resolver to map clients to a topology record. I always get 'None' for the region regardless of how my config is setup.

**Comment by antongavrik** [comment]
Providing a configuration example, logs where 'None' is being seen etc should help to understand this better.

**Comment by mattackerman808** [comment]
Hi Anton,

Unfortunately I can not provide details about this publicly. If you are interested in looking into this, is it possible for you to get a hold of me out of band to work on this issue? ackerman@apple.com

Thanks in advance.

-Matt

**Comment by antongavrik** [comment]
Is it possible to configure a simple testbed using private IP addresses/fictitious names?

A region of None would show up when a client IP address, as forwarded by pdns, does not fall in any of the networks defined in polaris-topology.yaml

**Comment by mattackerman808** [comment]
OK, I have cleaned up the config to the point where it still fails but removed almost all private info.

```
polaris-topology.yaml:

dc1:
    - 17.154.66.154/32
    - 17.154.66.155/32

dc2:
    - 17.133.240.64/32

dc3:
    - 17.173.66.179/32
    - 17.173.66.180/32
    - 17.172.128.16/32


```

```
polaris-lb.yaml:

pools:
    pool:
        monitor: http
        monitor_params:
            use_ssl: true
            hostname: buy.store.com
            url_path: /
        lb_method: twrr
        fallback: any
        members:
            17.154.66.154:
                name: server1
                weight: 1
            17.154.66.155:
                name: server2
                weight: 1
            17.133.240.64:
                name: server3
                weight: 1
            17.173.66.179:
                name: server4
                weight: 1
            17.173.66.180:
                name: server5
                weight: 1

global names
    buy.store.com:
        pool: pool
        ttl: 30
```

```
Logfile entry:

pdns[29732]: [remotebackend]:request: {"method":"lookup","parameters":{"qtype":"SOA","qname":"buy.store.com","remote":"17.172.128.16","local":"0.0.0.0","real-remote":"17.172.128.16/32","zone-id":-1}} result: [{'ttl': 60, 'qtype': 'SOA', 'qname': 'buy.store.com', 'content': 'polaris.matttest.com. hostmaster.polaris.matttest.com. 1 600 86400 1'}] pid: 30664 time taken: 0.000996
pdns[29732]: [remotebackend]:get_region() time taken: 0.000149 client region: None dist table used: {"index": 4, "num_unique_addrs": 5, "rotation": ["17.154.66.154", "17.173.66.180", "17.154.66.155", "17.133.240.64", "17.173.66.179"]} request: {"method":"lookup","parameters":{"qtype":"ANY","qname":"buy.store.com","remote":"17.172.128.16","local":"0.0.0.0","real-remote":"17.172.128.16/32","zone-id":-1}} result: [{'ttl': 30, 'qtype': 'A', 'qname': 'buy.store.com', 'content': '17.173.66.179'}] pid: 30664 time taken: 0.000436
```
