### ISSUE TITLE
issue with topology weighted round-robin

### ISSUE THREAD

**Issue by john-bakker** [polaris-gslb/polaris-gslb#33]
Hi, 

I got a question, on my master node i've configured my polaris with powerdns and I am using this configuration : 
polaris-lb.yaml

```
pools:
    www-example:
        monitor: tcp
        monitor_params:
            port: 22
            timeout: 1.0
        lb_method: twrr
        fallback: any
        members:
        - ip: 192.168.168.10
          name: master
          weight: 1
        - ip: 192.168.168.100
          name: minion-1
          weight: 1
        - ip: 192.168.168.101
          name: minion-2
          weight: 1

globalnames:
    www.example.com:
        pool: www-example
        ttl: 1

```

polaris-topology.yaml
```
Master:
- 192.168.168.10/32
Minions:
- 192.168.168.96/29
```

When I do a lookup from my masternode (master region) i get the proper repsonse where it is always giving me back 192.168.168.10

```
[root@salt log]#  dig www.example.com @192.168.168.10

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.47.rc1.el6_8.3 <<>> www.example.com @192.168.168.10
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8707
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;www.example.com.               IN      A

;; ANSWER SECTION:
www.example.com.        1       IN      A       192.168.168.10

;; Query time: 92 msec
;; SERVER: 192.168.168.10#53(192.168.168.10)
;; WHEN: Fri Jan 20 11:36:44 2017
;; MSG SIZE  rcvd: 49
```

However , when I'm doing exactly the same from my minion nodes (minions region) i'm getting responses where it gives me the IP of minion-1 and minion-2 , but it is also giving me the ip of the master.

Did I do something wrong in the configuration , or did i face a bug ? 

I can't find anything about a log on the polaris pages. Is there a log where i can trace these lookups ? i didn't see anything when running polaris with start-debug
`
