### ISSUE TITLE
let subdomain resolve to set of ip's using polaris

### ISSUE THREAD

**Issue by john-bakker** [polaris-gslb/polaris-gslb#40]
Hi Anton,

I was wondering if it is possible to let all subdomains of a certain address to the same set of ip addresses.

So not using a nameserver like below : 
```
zonenames:
    example.com
        pool: www-example
        ttl: 1
        nameservers:
        - name: ns1.example.com
          ttl: 14400
        - name: ns2.example.com
          ttl: 14400  
```

but more like :
```
    globalnames:
      .example.com.:
        pool: example.com.pool
        ttl: 1
```
using :
```
    pools:
      example.com.pool:
        monitor: tcp
        monitor_params:
          port: 443
          timeout: 5
          retries: 2
          interval: 10
        lb_method: wrr
        fallback: any
        members:
        - ip: 10.165.209.22
          name: lbapr1
          weight: 1
        - ip: 10.165.209.25
          name: lbapr2
          weight: 1
        - ip: 10.165.209.26
          name: lbapr3
          weight: 1
```

I want to have all subdomains like a.example.com b.example.com c.example.com all resolve to my 3 ip addresses on which i'm having HA proxy determing to where my traffic should go.

If I load this config as described above , polaris-gslb starts without a problem , and i do see the global name and the pool in the get-ppdns-state table : 
```

        "example.com": {
            "status": false,
            "fallback": "any",
            "lb_method": "wrr",
            "max_addrs_returned": 1,
            "dist_tables": {
                "_default": {
                    "num_unique_addrs": 3,
                    "rotation": [
                        "10.165.209.22",
                        "10.165.209.25",
                        "10.165.209.26"
                    ],
                    "index": 1
                }
            }
        },

```

although when i do a dig on one of my subdomains it doesn't resolve : 

```
dig john.example.com

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.47.rc1.el6_8.3 <<>> john.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 49183
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;john.example.com. IN   A

;; Query time: 20 msec
;; SERVER: 10.10.155.92#53(10.10.155.92)
;; WHEN: Wed Sep 27 11:09:34 2017
;; MSG SIZE  rcvd: 50

```

I would really appreciate your help

**Comment by antongavrik** [comment]
Each subdomain will need to be defined as a globalname referencing the same pool.
```
    globalnames:
      a.example.com:
        pool: example.com
        ttl: 1
      b.example.com:
        pool: example.com
        ttl: 1
```
